FROM registry.access.redhat.com/jboss-fuse-7-tech-preview/fuse-java-openshift

ENV JAVA_APP_JAR springboot-demo-0.0.1-SNAPSHOT.jar
ENV AB_OFF true
EXPOSE 8080
COPY springboot-demo-0.0.1-SNAPSHOT.jar /deployments
