---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deps090
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: s090
    spec:
      containers:
      - name: cons090
        image: jbossacr.azurecr.io/jboss-fuse-7-tech-preview/fuse-eap-openshift:v1
        env:
        - name: PRESERVE_JAVA_OPTS
          value: "false"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Xms1024m -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true"
        - name: Key1
          value: "VALUE1"
        command: ["/opt/eap/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"]
#        args: ["-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "-P=./test.properties"]
#      restartPolicy: OnFailure
